package com.system.cacheclean.storage

import android.content.Context
import android.util.Log
import com.system.cacheclean.db.dao.KeywordAudioDao
import com.system.cacheclean.model.AudioType
import com.system.cacheclean.model.Gender
import com.system.cacheclean.util.SilenceAudioGenerator
import java.io.File

/**
 * AudioResolver
 *
 * The single gatekeeper between CallStateManager and the filesystem.
 * Every audio file request during a live call goes through this class.
 *
 * CORE RULE: Gender is NEVER mixed within a session.
 *
 * PHASE 6 ADDITION — Silence Fallback:
 *   If a requested audio file cannot be resolved (no recordings yet on fresh
 *   install, or all files deleted), AudioResolver returns a generated
 *   500ms silence WAV instead of null.
 *
 *   This ensures the call engine always has something to play and the
 *   state machine never stalls on a null audio file.
 *
 *   Silence file location: filesDir/silence.wav (generated by SilenceAudioGenerator)
 */
class AudioResolver(
    private val storageManager: StorageManager,
    private val keywordAudioDao: KeywordAudioDao,
    private val context: Context? = null    // Optional: needed only for silence fallback
) {

    companion object {
        private const val TAG = "StealthGuard_Resolver"
    }

    // ─── Hook ─────────────────────────────────────────────────────────────────

    /**
     * Returns the active hook file for the given gender.
     * Falls back: active hook → first hook file → silence → null
     */
    fun resolveHook(gender: Gender): File? {
        // Try user-designated active hook
        storageManager.getActiveHook(gender)?.let {
            Log.d(TAG, "Hook [$gender]: active → ${it.name}")
            return it
        }
        // Fallback: first available file in hooks/
        storageManager.listFiles(gender, AudioType.HOOK).firstOrNull()?.let {
            Log.d(TAG, "Hook [$gender]: fallback → ${it.name}")
            return it
        }
        // Silence fallback (Phase 6)
        silenceFallback("Hook [$gender]")?.let { return it }

        Log.w(TAG, "Hook [$gender]: no hook files and no silence fallback.")
        return null
    }

    // ─── Response (Keyword-Matched) ───────────────────────────────────────────

    /**
     * Looks up keyword in Room DB and returns the correct gender's file.
     * Returns null (not silence) if no match — caller falls through to filler.
     * Must be called on a background thread (synchronous Room query).
     */
    fun resolveResponse(gender: Gender, keyword: String): File? {
        val entity = keywordAudioDao.findByKeyword(keyword.trim().lowercase())
        if (entity == null) {
            Log.d(TAG, "Response [$gender]: no DB entry for '$keyword'")
            return null
        }

        val path = when (gender) {
            Gender.GENTS -> entity.gentsAudioPath
            Gender.LADY  -> entity.ladyAudioPath
        }

        if (!storageManager.isPathValid(path)) {
            Log.w(TAG, "Response [$gender]: invalid path for '$keyword'")
            return null
        }

        Log.d(TAG, "Response [$gender]: matched '$keyword' → $path")
        return File(path!!)
    }

    // ─── Filler (Random Fallback) ─────────────────────────────────────────────

    /**
     * Returns a random filler file for the given gender.
     * Falls back to silence if no fillers recorded yet.
     */
    fun resolveRandomFiller(gender: Gender): File? {
        val fillers = storageManager.listFiles(gender, AudioType.FILLER)
        if (fillers.isNotEmpty()) {
            val picked = fillers.random()
            Log.d(TAG, "Filler [$gender]: picked → ${picked.name}")
            return picked
        }
        // Silence fallback (Phase 6)
        silenceFallback("Filler [$gender]")?.let { return it }

        Log.w(TAG, "Filler [$gender]: no filler files and no silence fallback.")
        return null
    }

    // ─── Silence Fallback (Phase 6) ───────────────────────────────────────────

    /**
     * Returns the silence WAV file if context is available and the file exists.
     * Logs a warning identifying which audio type triggered the fallback.
     */
    private fun silenceFallback(callerLabel: String): File? {
        val ctx = context ?: return null
        val silenceFile = SilenceAudioGenerator.getFile(ctx)
        return if (silenceFile.exists() && silenceFile.length() > 44) {
            Log.w(TAG, "$callerLabel: no audio files — using silence fallback")
            silenceFile
        } else {
            null
        }
    }
}
